### ISSUE TITLE
[Enhancement]: Optimize System Monitoring in waybar

### ISSUE THREAD

**Issue by BarutSRB** [meowrch/meowrch#11]
The continuous system monitoring scripts in waybar might be causing high CPU usage.

- system-info.py (runs every 2 seconds)
- volume.sh (runs every 1 second)
- brightness.sh (continuous monitoring)

The system monitor script queries multiple system stats frequently
It uses several external libraries (psutil, GPUtil, pyamdgpuinfo)
No caching or throttling mechanisms are implemented

Tested on Laptop Intel N100, it is a low end cpu but with other preconfigs it is not utilizing 40-50% of CPU and I love your preconfig and wish to use it but it needs optimization for system monitoring.

**Comment by DIMFLIX-OFFICIAL** [comment]
Yeah, that's a good suggestion. 
But I have no idea how this script can be optimized for even lower CPU usage.

Your methods will cause damage. After all, caching will make the results unreliable for the current time. And by trotting I don't understand what you mean. 
The only thing I can assume is that you meant to increase the time between requests to the script. But this again will not show reliable results at the current time. 

It's everyone's choice at what interval to request information about PC resource utilization.

The only thing you can do is to use the script constantly. After all, now it is called, does its work and closes. 
Most likely it would be faster and less resource-hungry to keep it open all the time and just request information while it is running. This will reduce the cost of reading arguments, for example.

No more optimization ideas, unfortunately.
