### ISSUE TITLE
Не работатет кнопка уведомлений

### ISSUE THREAD

**Issue by MEWOOO** [meowrch/meowrch#6]
Не работает кнопка уведомлений в правом верхнем углу в режиме работы через bspwm

**Comment by DIMFLIX-OFFICIAL** [comment]
Исправлено в коммите 9e23089ad316ea8d2a6f3bf25b601f2cb782298d.

Поскольку автоматическое обновление конфигураций в системе с помощью GitHub в настоящее время не предусмотрено, вы можете вручную внести изменения в свои конфигурации, опираясь на исправления из указанного коммита.
