### ISSUE TITLE
[Custom]: When change gaps and active boader, it resets automatically 

### ISSUE THREAD

**Issue by fernand3z** [meowrch/meowrch#8]
``` .config/hypr/custom-prefs.conf```

```

# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 3
    col.active_border = rgb(b4befe) rgb(f5c2e7) 45deg
        col.inactive_border = rgba(00000000)
    layout = dwindle
    resize_on_border = true
}

``` 

when i change gaps_out = 8 => 1 and border_size = 3 => 1, it changes. But after restarting the pc, it changed back to automatically.

**Comment by fernand3z** [comment]
> Love ≽ܫ≼ meowrch btw

**Comment by DIMFLIX-OFFICIAL** [comment]
The problem is that you are changing a file that is changed by the theme.

Basically, when you reboot, you have a theme installed.

It replaces some configurations. Including `.config/hypr/custom-prefs.conf`

In order to prevent your settings from being reset, you need to edit this configuration in the folder with your theme `~/.config/meowrch/themes/<YOUR_ACTIVE_THEME>/hyprland-custom-prefs.conf`

**Comment by fernand3z** [comment]
Ohh thanks, man. Is it the same with the wallpaper, because when i use a downloaded picture to set as background, it changes when reboot. Could you give the location of the file needs to be changed.

**Comment by DIMFLIX-OFFICIAL** [comment]
You need to add a new photo to the folder `~/.config/meowrch/wallpapers/`.

After that, edit the file "~/.config/meowrch/config.yaml". You need to add the path to your new wallpaper to the "custom-wallpapers" section. Or if you want to add for a specific theme, then each theme has a "available_wallpapers" section. 

You can find out more about customization in our [wiki page](https://github.com/meowrch/meowrch/wiki/3-‐-Кастомизация#своя-тема--смена-обоев).

But it's in Russian. You'll need a translator.
Soon I will make exactly the same page, only in English :)

**Comment by fernand3z** [comment]
@DIMFLIX-OFFICIAL thanks so much man. Im loving the meowrch.
